### ISSUE TITLE
App crashes when clicked on Connect Controller - connected via Bluetooth

### ISSUE THREAD

**Issue by Aduser345** [WujekFoliarz/DualSenseY#1]
Hi,
I have connected my controller using Bluetooth before opening the app and when I Click on the Connect Controller button, the app crashes and its not even able to close through Task Manager.
Have to go to details section in Task Manager to End Process Tree.

I have attached screenshot please have a look
![Screenshot 2024-07-22 204906](https://github.com/user-attachments/assets/33442d5f-7412-4e94-92b3-6dce96913652)

**Comment by WujekFoliarz** [comment]
Try the latest version
