### ISSUE TITLE
Missing Audio settings and crash when connected with usb

### ISSUE THREAD

**Issue by osmnbtrclk** [WujekFoliarz/DualSenseY#2]
First of all I want to thank you for your time and efforts.

When I connect to dualsense using bluetooth I cant change sound settings.

<img width="441" alt="image" src="https://github.com/user-attachments/assets/8c75be9f-0855-4320-9b1c-32bc9dc84c7b">

And when I try to while connected with usb program crashes

![image](https://github.com/user-attachments/assets/9b4a30bb-434a-4847-808a-435d8857ca9f)

I am using Windows 11 AtlasOS, maybe because of this speaker doenst work I dont know, before the changing to AtlasOS speakers was working but rightnow it doesnt work. Similar problem in the DS4windows but not on the DSX in the DSX speakers work without problem.

**Comment by WujekFoliarz** [comment]
Download the newest version and report back.

**Comment by WujekFoliarz** [comment]
As for bluetooth - DualSense doesn't support audio wirelessly on PC.

**Comment by osmnbtrclk** [comment]
Thank you, it works now.
