### ISSUE TITLE
Audio Passthrough / haptic feedback will stop after 17-18 seconds

### ISSUE THREAD

**Issue by Ize-dev** [WujekFoliarz/DualSenseY#3]
Hello,
when i enable audio passthrough it will stop after exactly 17-18 seconds. The audio and haptic feedback stops.

It can be enabled again by disabling the checkbox and renabling it right away but then it stops again after the same time as if a timer is running in the background.

**Comment by WujekFoliarz** [comment]
What audio device do you have set as default output in windows

**Comment by WujekFoliarz** [comment]
Check if the default audio default isnt being switched durning audio passthrough somehow

**Comment by Ize-dev** [comment]
It stays the same, i can repeatedly enable / disable audio passthrough and it will continue to work, alsoi can directly disable / enable it again after it stops working to make it work again.

**Comment by WujekFoliarz** [comment]
Try the latest version, not sure if it will help

**Comment by Ize-dev** [comment]
It definately helped. 

When i use the onboard Realtek audio (stereo) it works as it should, no more sudden stops and no delay between the sound and the controller feedback.

However when i switch to my TV as the sound output device, which gets a dolby atmos signal from my pc, the sound is delayed by a few seconds, and "screechy"... it doesn't suddenly stop though so thats a win i guess :D

**Comment by WujekFoliarz** [comment]
Also, when u change the audio output try to restart the app.

**Comment by Ize-dev** [comment]
I've fixed it. :D

In "/Wujek-Dualsense-API/Wujek Dualsense API/HapticFeedback.cs" you didn't account for more than 2 channels when defining the wave format... you should probably check the source devices audio- / waveformat and clone that exactly (or closely).

If i define the wave format like this: `public BufferedWaveProvider bufferedWaveProvider = new BufferedWaveProvider(WaveFormat.CreateCustomFormat(WaveFormatEncoding.IeeeFloat, 48000, 8, 32, 8, 8));`

It works fine like on the normal audio device because (atleast in my case) my atmos output is 7+1 = 8 channels

**Comment by WujekFoliarz** [comment]
I actually tried to change that a few days ago but it results in screechy audio on my device

**Comment by WujekFoliarz** [comment]
Maybe I could just change the channel count dynamically? I'll Play around with it later today

**Comment by Ize-dev** [comment]
> I actually tried to change that a few days ago but it results in screechy audio on my device
Same thing happened to me but in reverse when i used my atmos tv out :D

> Maybe I could just change the channel count dynamically? I'll Play around with it later today
Awesome.

**Comment by WujekFoliarz** [comment]
Ok seems like we've found the problem cause

**Comment by WujekFoliarz** [comment]
I'll tell you when I update the program

**Comment by WujekFoliarz** [comment]
Also since you're on it try to play around with this

```
            MultiplexingWaveProvider multiplexingWaveProvider = new MultiplexingWaveProvider(new BufferedWaveProvider[] {
                bufferedWaveProvider,
            }, 4);

            multiplexingWaveProvider.ConnectInputToOutput(0, 0);
            multiplexingWaveProvider.ConnectInputToOutput(0, 1);
            multiplexingWaveProvider.ConnectInputToOutput(0, 2);
            multiplexingWaveProvider.ConnectInputToOutput(1, 3);
```

Last 2 lines connect left and right channel to the controller actuators
2 is left
3 is right

0 is system audio's left channel and 1 is right

Try to find out which channel is which on dolby atmos

**Comment by WujekFoliarz** [comment]
So only change the variables on the left

**Comment by Ize-dev** [comment]
I've increased the first number from 0 to 7 with no effect after the number 2.
I guess it's not that easy :P

However it seems to still work fine, i've tested it with Elden Ring (modded) and System Shock Remastered, but send audio and haptics.

The only game i couldn't get to work so far is Black Myth Wukong, i even tried disabling steam input (both options, global and on the game) but there is no audio and no haptics.

**Comment by Ize-dev** [comment]
Yes, both sides vibrate correctly

**Comment by WujekFoliarz** [comment]
Only one at the time right?
Btw I updated the API code, it should change channel count when u call dualsense.SetNewPlaybackDevice();

**Comment by WujekFoliarz** [comment]
nvm i scrapped it dont do anything, just wait for my app to update

**Comment by WujekFoliarz** [comment]
Ok try the latest version, I wasted 2.5 hours on this cuz WPF apparently doesn't like MTA threads and the solution I wrote in 5 minutes works lmao.
Pls work 🙏

**Comment by WujekFoliarz** [comment]
Ok I have tried it on virtual cable and it works, but SL/SR/C/SUB channels dont go through, only L/R. I'll play around with it later tommorow.

**Comment by WujekFoliarz** [comment]
Ok I've tried this video and it works ? https://www.youtube.com/watch?v=_TX--Fku9NQ&t=62s
weird

**Comment by WujekFoliarz** [comment]
whatever just tell me if everything works for you, if so i will leave it as is

**Comment by Ize-dev** [comment]
Seems to work fine so far :D

**Comment by WujekFoliarz** [comment]
Ok keep testing, close the issue when u think its  fine
