### ISSUE TITLE
When UDP is on and i try to emulate xbox 360, DualSenseY crashes.

### ISSUE THREAD

**Issue by Smoodie7** [WujekFoliarz/DualSenseY#4]
Note: I have DSX.exe in the folder if that detail is important.

**Comment by WujekFoliarz** [comment]
Doesn't happen to me, what hidhide version?
![image](https://github.com/user-attachments/assets/9540cd93-c33b-4dc2-aeda-0486ee5d71ef)

**Comment by Smoodie7** [comment]
I have the same version; maybe consider adding an enhanced logging system to more easily diagnose user issues? (Btw, great project—it has completely replaced DSX and DS4 for me.)
![Capture d’écran 2024-09-30 161521](https://github.com/user-attachments/assets/c0712625-9fdb-48c3-a231-861f55b3f6c3)

**Comment by WujekFoliarz** [comment]
Try 5.0, some kind of error should pop up

**Comment by Smoodie7** [comment]
i'll do it later this day, thanks for this update!
