### ISSUE TITLE
Multiple controller support at the same time ?

### ISSUE THREAD

**Issue by Virtualchronos** [WujekFoliarz/DualSenseY#5]
Hello !

First, congratulations for the hard work.
I'm still an old gamer with four PS3 controllers and the old DS3 tool who allow to emulate 4 xbox controller at the same time.

I naturaly baught 3 dualsense controllers to do the same but unfortunately, there seems to be no way to emulate multiple xbox controllers with this tool ?

**Comment by WujekFoliarz** [comment]
I recommend steam input for multi controller play

**Comment by Virtualchronos** [comment]
A lot of my games are not steam compatible. If you know another way ?

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by WujekFoliarz** [comment]
You can add any game as a non-steam game. Bottom left corner in steam client

**Comment by Virtualchronos** [comment]
honestly for many reasons, I hate using steam except when i've really no other choice. That's why i'm trying to get any tool who could do multiplayer controller emulation support without it.

**Comment by WujekFoliarz** [comment]
okey i'll look into it

**Comment by WujekFoliarz** [comment]
Would an option to run multiple DualSenseY instances at the same time be enough?

**Comment by Virtualchronos** [comment]
no idea. It would be a good start to try

**Comment by WujekFoliarz** [comment]
It should be enough, i'll just replace controller 1,2,3,4 with windows device id and allow multiple instances running at the same time.

**Comment by Virtualchronos** [comment]
I'll try as soon as you'll give me a test release ^.^

**Comment by WujekFoliarz** [comment]
That will be probably tommorow

**Comment by Virtualchronos** [comment]
No problem ! I'll give you the feedback of the fix tommorow then ^^

**Comment by WujekFoliarz** [comment]
![{27E309C1-82AA-4097-AF0F-1F837D8CF2BF}](https://github.com/user-attachments/assets/97e8e8c4-f76f-4743-b014-c7bc84c874b2)

will upload soon

**Comment by Virtualchronos** [comment]
Nice ! so to resume, you can now launch as many instances of dualsenseY as you have players and then activate xbox emulation for each of them one by one

**Comment by WujekFoliarz** [comment]
yeah try it out

**Comment by Virtualchronos** [comment]
WORKING LIKE A CHARM ! 👍 

The way to do it is not the best but now multiplayer can be done and DualsenseY is the ONLY DOWNLOADABLE tool to have this function.

**Comment by WujekFoliarz** [comment]
Good to hear

**Comment by Virtualchronos** [comment]
The only little problem is the configuration wich i think should be linked to the controller number profile to simplify the setup. Or maybe a cfg who can have in one file all the different controllers options

**Comment by WujekFoliarz** [comment]
There is a discord in this github page readme.
