### ISSUE TITLE
L2 and R2 button don`t work on ds4 controller emulation

### ISSUE THREAD

**Issue by SergioEtreros** [WujekFoliarz/DualSenseY#8]
hi, I encounter an issue when i connect my dualsense controller and emulate a ds4 controller, L2 and R2 buttons don't work on games, but it does on game device control panel, there i can see them working, but ingame they do nothing, if i emulate xbox controller or disable emulation and connect the controller wired they work, but emulating ds4 they don't, bt nor wired.

![image](https://github.com/user-attachments/assets/203c6310-444a-46ba-aa9c-6f0d25c24ada)

greetings

**Comment by WujekFoliarz** [comment]
Check here
https://hardwaretester.com/gamepad

**Comment by WujekFoliarz** [comment]
try the newest version, close the issue if it's fixed

**Comment by SergioEtreros** [comment]
yeah it works, thanks :D
